//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contaxt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactExam
    {
        public int id { get; set; }
        public string name { get; set; }
        public int phone { get; set; }
        public string groupname { get; set; }
        public System.DateTime dateofhire { get; set; }
        public System.DateTime dateofbirth { get; set; }
    }
}
