//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mySeviceAplication.Areas.HelpPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentId { get; set; }
        public Nullable<int> getGrade { get; set; }
        public int StudentId { get; set; }
        public int CourceId { get; set; }
    
        public virtual Cource Cource { get; set; }
        public virtual Student Student { get; set; }
    }
}
